[WIP] Add virtualizing wrap panel
AvaloniaUI/Avalonia.Labs pull request #92
Opened 2024-11-22 14:48 UTC by timunie

This is still in WIP mode 

- [ ] different sized items are not yet calculated correctly 
- [ ] switching orientation needs better handling

2025-07-07 11:50 UTC, timunie commented
I think the code is ready for a first review.

2025-07-24 06:09 UTC, timunie commented
If one has different sized items, it is hard to predict how to navigate in this scenario, at least when it comes to navigate rows. Therefore, I decided to disable row navigation when items are of different size. However, a developer can override `Navigate***()` and implement the behavior as needed. 

From my point of view, the control is ready for review.

2026-06-15 14:33 UTC, emmauss commented
Is this ready to review?

2026-06-15 15:21 UTC, timunie commented
Hey @emmauss , 

I am using this control here (don't mind the branch name, it is a test-bed): https://github.com/timunie/MahApps.Avalonia.IconPacks.Testbed/tree/test/RemovingFluentAvaloniaReference

You can test the Control live online: https://timunie.github.io/MahApps.Avalonia.IconPacks.Testbed/

<img width="1151" height="745" alt="image" src="https://github.com/user-attachments/assets/dc1adab4-2738-442a-8d77-1dc3c03f856f" />


Let me know your thoughts

2026-09-02 09:41 UTC, emmauss requested changes

2026-09-02 09:41 UTC, emmauss commented on src/Avalonia.Labs.Notifications/Avalonia.Labs.Notifications.csproj
> +    <TargetFrameworks>net8.0</TargetFrameworks>
Don't change unrelated projects

2026-09-07 08:13 UTC, emmauss commented
Tests failing

2026-09-09 09:36 UTC, merged